Repository Rigtch/rigtch-fm-www, pull requests merged in 2023-12, with the labels that each got.

#125 Unit testing
  app/profile/page.spec.tsx
Labels: testing

#129 feat(components): create footer
  app/components/footer.tsx
  app/layout.tsx
Labels: enhancement

#141 `PlaybackCard` change button icon immediatel y after click
  app/context/playback-state.spec.tsx
  app/context/playback-state.tsx
  app/profile/components/playback/card.tsx
Labels: enhancement

#142 chore(.github/workflows/main): use node `v20.10.0`
  .github/workflows/main.yml
Labels: configuration

#145 feat(navigation/bar): fix navigation item when display name is short
  app/components/navigation/bar.tsx
Labels: enhancement

#151 feat(navigation/bar): fix display name overflow and remove rigtch fm on mobile
  app/components/navigation/bar.tsx
Labels: enhancement, invalid

#159 chore(eslint): add new rules
  .eslintrc
  .eslintrc.cjs
  app/api/authorize/route.spec.ts
  app/api/authorize/route.ts
  app/api/fetchers/fetch-api.spec.ts
  app/api/fetchers/fetch-api.ts
  app/api/fetchers/get-last-tracks.spec.ts
  app/api/fetchers/get-playback-state.spec.ts
  app/api/fetchers/get-refresh.spec.ts
  app/api/fetchers/get-top-artists.spec.ts
  app/api/fetchers/get-top-tracks.spec.ts
  app/api/hooks/use-last-tracks-query.spec.tsx
  app/api/hooks/use-playback-state-query.spec.tsx
  app/api/hooks/use-toggle-playback-state.spec.tsx
  app/components/common/see-more-button.tsx
  app/components/navigation/bar.tsx
  app/components/ui/progress.tsx
  app/components/ui/toggle-group.tsx
  app/context/playback-state.spec.tsx
  app/context/playback-state.tsx
  app/error-boundary.tsx
  app/hooks/use-auth-cookies.spec.tsx
  app/page.tsx
  app/profile/components/items/item.tsx
  app/profile/components/items/top-card.tsx
  app/profile/components/playback/card.tsx
  app/profile/components/profile/avatar.spec.tsx
  app/profile/page.spec.tsx
  app/profile/page.tsx
  app/profile/recently-played/page.tsx
  app/profile/top/genres/page.tsx
  app/utils/cn.spec.ts
  app/utils/formatters/artists.spec.ts
  app/utils/formatters/search-params.spec.ts
  package.json
  vitest.config.ts
  yarn.lock
Labels: configuration

#161 fix(playback/card): static image width and height
  app/profile/components/playback/card.tsx
Labels: bug, invalid

#163 feat(common/relative-time): add test coverage
  app/components/common/relative-time.spec.tsx
  app/profile/components/playback/card.spec.tsx
Labels: enhancement
