Repository Rigtch/rigtch-fm-www, pull requests merged in 2023-11, with the labels that each got.

#112 fix(components/common/relative-time): add `suppressHydrationWarning` attribute to `p` element
  app/components/common/relative-time.tsx
Labels: invalid

#113 fix(profile/top/template): fix select view positioning on mobile
  app/profile/top/template.tsx
Labels: invalid

#109 feat(home): add connect to spotify card
  app/components/connect/card.tsx
  app/page.tsx
Labels: enhancement

#124 tests for `ProfileLayout`
  app/profile/components/profile/card.tsx
  app/profile/layout.spec.tsx
Labels: testing
