Repository Rigtch/rigtch-fm-www, pull requests merged in 2023-08, with the labels that each got.

#57 refactor(pages): replace about page with home and home page with profile
  src/components/navigation-bar.tsx
  src/components/profile/info.spec.tsx
  src/components/profile/info.tsx
  src/pages/about.tsx
  src/pages/api/authorize.ts
  src/pages/index.tsx
  src/pages/profile.tsx
  src/sections/profile/analysis.tsx
  src/sections/profile/index.ts
  src/sections/profile/last-tracks.spec.tsx
  src/sections/profile/last-tracks.tsx
  src/sections/profile/top-artists.spec.tsx
  src/sections/profile/top-artists.tsx
  src/sections/profile/top-genres.spec.tsx
  src/sections/profile/top-genres.tsx
  src/sections/profile/top-tracks.spec.tsx
  src/sections/profile/top-tracks.tsx
Labels: refactor

#59 fix(components/profile): display first letter of `displayName` if user has no profile image
  src/components/profile/card.tsx
  src/components/profile/info.tsx
Labels: invalid

#67 refactor(components/select-time-range): reverse items
  src/components/select-time-range.tsx
Labels: refactor

#69 feat(element/top-one-card): remove stars from image
  src/components/element/card.tsx
  src/components/element/top-one-card.tsx
Labels: enhancement
