Repository Rigtch/rigtch-fm-www, pull requests merged in 2024-07, with the labels that each got.

#365 feat(app/page): fix overlapping
  app/components/navigation/navigation-bar.tsx
  app/layout.tsx
  app/page.tsx
Labels: bug, invalid

#376 feat: change playtime -> playTime
  app/api/types/rigtch-stats-response.ts
  app/components/items/cards/item-top-card.spec.tsx
  app/components/items/cards/item-top-card.stories.tsx
  app/components/items/cards/item-top-card.tsx
  app/components/items/examples.ts
  app/components/items/genre/genre-chip.spec.tsx
  app/components/items/genre/genre-chip.stories.tsx
  app/components/items/genre/genre-chip.tsx
  app/components/items/list/items-list-element.spec.tsx
  app/components/items/list/items-list-element.stories.tsx
  app/components/items/list/items-list-element.tsx
  app/components/items/list/items-list.spec.tsx
  app/components/items/list/items-list.stories.tsx
  app/components/items/list/items-list.tsx
  app/components/items/props.ts
  app/profile/components/common/selects/select-stats-measurement.spec.tsx
  app/profile/components/common/selects/select-stats-measurement.tsx
  app/profile/sections/top-genres-section.stories.tsx
  app/profile/sections/top-genres-section.tsx
  tests/snapshots/genre-chip.spec.tsx.snap
  tests/snapshots/items-list-element.spec.tsx.snap
  tests/snapshots/items-list.spec.tsx.snap
Labels: invalid

#387 fix(components/sidebar): top albums page time range
  app/components/sidebar/sidebar.tsx
  tests/snapshots/sidebar.spec.tsx.snap
Labels: bug

#384 refactor(skeletons): rename `SkeletonSection` -> `SectionSkeleton`
  app/profile/[id]/@analysis/loading.tsx
  app/profile/[id]/@top/@albums/loading.tsx
  app/profile/[id]/@top/@artists/loading.tsx
  app/profile/[id]/@top/@genres/loading.tsx
  app/profile/[id]/@top/@tracks/loading.tsx
  app/profile/[id]/top/albums/loading.tsx
  app/profile/[id]/top/artists/loading.tsx
  app/profile/[id]/top/genres/loading.tsx
  app/profile/[id]/top/tracks/loading.tsx
  app/profile/sections/analysis-section.skeleton.tsx
  app/profile/sections/items-section.stories.tsx
  app/profile/sections/top-albums-section.skeleton.tsx
  app/profile/sections/top-artists-section.skeleton.tsx
  app/profile/sections/top-genres-section.skeleton.tsx
  app/profile/sections/top-tracks-section.skeleton.tsx
Labels: refactor

#393 fix(playback-card.skeleton): image width
  app/profile/components/playback/playback-card.skeleton.tsx
  app/profile/components/playback/playback-card.tsx
Labels: invalid

#400 fix(profile/sections/items): children width
  app/profile/sections/items-section.tsx
  tests/snapshots/items-section.spec.tsx.snap
Labels: invalid

#401 fix(components/items/list/element): element height
  app/components/items/list/items-list-element.tsx
  tests/snapshots/items-list-element.spec.tsx.snap
  tests/snapshots/items-list.spec.tsx.snap
  tests/snapshots/items-section.spec.tsx.snap
Labels: invalid

#403 fix(profile/components/common/selects): use `value` prop instead of `defaultValue`
  app/profile/components/common/selects/select-stats-measurement.spec.tsx
  app/profile/components/common/selects/select-stats-measurement.tsx
  app/profile/components/common/selects/select-time-range.spec.tsx
  app/profile/components/common/selects/select-time-range.tsx
  app/profile/components/common/selects/select-view.spec.tsx
  app/profile/components/common/selects/select-view.tsx
  bun.lockb
  package.json
Labels: bug

#412 fix(profile/sections/top-genres): wrap `children` with div and center it
  app/profile/sections/top-genres-section.tsx
  tests/snapshots/top-genres-section.spec.tsx.snap
Labels: invalid

#414 fix(profile/top/layout): show stats measurement on top items total pages
  app/profile/[id]/top/layout.tsx
Labels: bug

#429 fix(profile/@analysis/page): reverse progress colors and fix tempo
  app/profile/[id]/@analysis/page.tsx
Labels: invalid
