Repository Rigtch/rigtch-fm-www, pull requests merged in 2024-06, with the labels that each got.

#299 feat(profile): fix open in spotify button width
  app/profile/components/items/top-card.tsx
  app/profile/components/profile/card.tsx
Labels: invalid

#301 feat(profile/items): fix text width on smaller devices
  app/profile/components/items/item.tsx
  app/profile/components/items/top-card.tsx
Labels: invalid

#304 feat(profile/playback/card): fix artists overflow
  app/profile/components/playback/card.tsx
Labels: invalid

#314 chore(.github/workflows): add dependabot update bun lock
  .github/workflows/dependabot-update-bun-lock.yml
Labels: configuration

#313 254 hide rigtch logo on mobile and display hamburger
  app/components/navigation/bar.tsx
Labels: invalid

#327 feat: fix playback card image skeleton
  app/components/items/list/items-list.tsx
  app/profile/components/playback/playback-card.tsx
  app/utils/get-image.ts
Labels: invalid

#328 feat(album/page): add copyright
  app/(items)/album/[album-id]/page.tsx
  app/api/types/album.ts
Labels: enhancement
